import pyautogui
import time
time.sleep(2)

print("Нажимаем 'w'")
pyautogui.keyDown("w")
time.sleep(2)
print("Отпускаем 'w'")
pyautogui.keyUp("w")
time.sleep(0.50)
print("Нажимаем 'd'")
pyautogui.keyDown("d")
time.sleep(2)
print("Отпускаем 'd'")
pyautogui.keyUp("d")
time.sleep(0.50)
print("Нажимаем 's'")
pyautogui.keyDown("s")
time.sleep(2)
print("Отпускаем 's'")
pyautogui.keyUp("s")
time.sleep(0.50)
print("Нажимаем 'a'")
pyautogui.keyDown("a")
time.sleep(2)
print("Отпускаем 'a'")
pyautogui.keyUp("a")
time.sleep(0.50)

