import turtle
r = turtle.Pen()
r.color("yellow")
r.begin_fill()
r.circle(90)
r.fillcolor("yellow")
r.end_fill()
r.color("blue")
r.begin_fill()
r.forward(200)
r.right(90)
r.forward(200)
r.right(90)
r.forward(400)
r.right(90)
r.forward(200)
r.right(90)
r.forward(400)
r.fillcolor("blue")
r.end_fill()
turtle.mainloop()