import turtle
e = turtle.Pen()
e.color("red")
e.pensize(3)
e.begin_fill()
e.forward(100)
e.left(90)
e.forward(100)
e.left(90)
e.forward(100)
e.left(90)
e.forward(100)
e.left(90)
e.fillcolor("pineapple")
e.end_fill()
turtle.mainloop()